# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.CharField(help_text=b'10 digit mobile number', max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField(help_text=b'6 digit valid Postel code', validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(999999)])),
                ('status', models.CharField(choices=[(b'initiated', b'Initiated'), (b'processing', b'Processing'), (b'dispatched', b'Dispatched')], max_length=20)),
                ('payment_option', models.CharField(choices=[(b'cod', b'Cash On Delievery')], max_length=10)),
                ('items', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
