# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20160213_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=225),
        ),
    ]
